#pragma once

#define LV_FONT_MONTSERRAT_48 0
#define LV_FONT_MONTSERRAT_64 0
#define LV_FONT_MONTSERRAT_72 1
#define LV_FONT_MONTSERRAT_96 0
#define LV_FONT_MONTSERRAT_128 0

#define LV_FONT_ORBITRON_MEDIUM_24 0
#define LV_FONT_ORBITRON_MEDIUM_32 0
#define LV_FONT_ORBITRON_MEDIUM_36 0
#define LV_FONT_ORBITRON_MEDIUM_42 0
#define LV_FONT_ORBITRON_MEDIUM_48 0
#define LV_FONT_ORBITRON_MEDIUM_64 0
#define LV_FONT_ORBITRON_MEDIUM_72 0
#define LV_FONT_ORBITRON_MEDIUM_96 0
#define LV_FONT_ORBITRON_MEDIUM_128 0

#include "fonts/montserrat/lv_font_montserrat.h"
#include "fonts/orbitron/orbitron.h"
